name: test_clash_latency
on:
  workflow_dispatch:
jobs:
  test_clash_latency:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - run: pip install requests
    - run: sudo python test_clash_latency.py
# 提交           
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add xxx.yaml
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') staticsub node update"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main
