name: test_clash_latency
on:
  workflow_dispatch:
jobs:
  test_clash_latency:

# 基本系统配置
    runs-on: ubuntu-latest
    steps:
    - name: 迁出代码
      uses: actions/checkout@v3
    - name: 安装Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - name: 加载缓存
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/run_in_Actions/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: 设置时区
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
      
# 安装依赖和工具
    - name: 安装依赖
      run: |
        pip install -r ./requirements.txt
    #- run: pip install requests
    - run: sudo python test_clash_latency.py
# 提交           
    - name: 提交更改
      run: |                 
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git pull origin main
        git add xxx.yaml
        git commit -m "$(date '+%Y-%m-%d %H:%M:%S') staticsub node update"
    - name: 推送更改
      uses:  ad-m/github-push-action@master
      with:
        branch: main
